#!/bin/bash

# This script is to be run in a TravisCI context.
set -ex

if [ -n "$GH_TOKEN" ]; then
    source activate base

    make clean
    ablog build

    ls -lah _website

    if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        git clone https://github.com/conda-forge/blog.git blog_repo
        pushd blog_repo
        git checkout gh_pages
        cp -r ../_website/* .
        touch .nojekyll
        git add -A :/
        git commit -m "[ci skip] ran ablog build" || true
        git remote add pushable https://${GH_TOKEN}@github.com/conda-forge/blog.git/ > /dev/null

        # Update the remotes before pushing and check the status.
        # This should give us more info if the push will not be
        # a simple fast-forward push.
        git fetch --all 2> /dev/null
        git branch -u pushable/gh_pages
        git status
        git push pushable gh_pages:gh_pages 2> /dev/null
        popd
    fi
fi
