name: deploy

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
      
      - name: install deps
        shell: bash -l {0}
        run: |
          mamba install --file requirements.txt --yes --quiet

      - name: build site
        shell: bash -l {0}
        run: |
          make clean
          ablog build || {
            cat /tmp/sphinx-err-* && exit 1
          }
          cp _website/blog/atom.xml _website/atom.xml

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_website
          user_name: conda-forge-curator[bot]
          user_email: 79913779+conda-forge-curator[bot]@users.noreply.github.com
